#!/usr/bin/env ruby

require 'bundler/setup'
require 'pry'
require 'edsl'
require 'edsl/page_object'

# Simple class to represent the initial search screen
class GoogleSearchPage < EDSL::PageObject::Page
  page_url 'https://www.google.com'

  TEST_HOOKS = CptHook.define_hooks do
    after(:set).call(:search)
  end
  text_field(:query, name: 'q', hooks: TEST_HOOKS)
  button(:search, name: 'btnK')
end

class AppBar < EDSL::PageObject::Section
  div(:results_stats, id: 'resultStats')
end

class SearchResult < EDSL::PageObject::Section
  h3(:title, index: 0)
  link(:result_link, index: 0, default_method: :href)
end

class GoogleResultsPage < GoogleSearchPage
  section(:app_bar, AppBar, id: 'appbar')
  sections(:search_results, SearchResult, id: 'search', item: { how: :divs, class: 'g' })
end

module GoogleDemo
  extend EDSL::PageObject::Navigation

  query = ARGV[0] || 'ruby'

  @browser = Watir::Browser.new :chrome, headless: true
  visit(GoogleSearchPage).populate_with( query: query)

  on(GoogleResultsPage) do |page|
    puts "There are #{page.app_bar.results_stats.strip} for #{query}"
    result = page.search_results.first
    puts "The first result is titled \"#{result.title}\" and points to #{result.result_link}"
  end
end
